apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-sesloqdd
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/go-sesloqdd:234f13b246e613a144b4e3020a00b0d72cc69acc@sha256:1d1bcc95b714f4ce4fdadfb331c5b9b3ec1a48a61f286b0c5ee7d180e7aa8bf7
          name: container-image
